name: Genarate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
  
jobs:
  builds:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
